# Generated by Django 4.2.30 on 2026-09-10 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('token_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the research paper.', max_length=512)),
                ('abstract', models.TextField(help_text='Abstract of the paper.')),
                ('research_area', models.CharField(choices=[('AI_ML', 'Artificial Intelligence & Machine Learning'), ('NLP', 'Natural Language Processing'), ('COMPUTER_VISION', 'Computer Vision'), ('DATA_SCIENCE', 'Data Science'), ('CYBERSECURITY', 'Cybersecurity'), ('SOFTWARE_ENGINEERING', 'Software Engineering'), ('NETWORKING', 'Networking'), ('DATABASE', 'Database Systems'), ('HCI', 'Human-Computer Interaction'), ('ROBOTICS', 'Robotics'), ('BIOINFORMATICS', 'Bioinformatics'), ('QUANTUM_COMPUTING', 'Quantum Computing'), ('OTHER', 'Other')], default='OTHER', help_text='Primary research area.', max_length=50)),
                ('keywords', models.CharField(help_text='Comma-separated list of keywords.', max_length=255)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('TEXT_EXTRACTED', 'Text Extracted'), ('INDEXED', 'Indexed'), ('AI_ANALYZED', 'AI Analyzed'), ('EVALUATED', 'Evaluated'), ('FAILED', 'Failed')], default='UPLOADED', help_text='Current processing status of the paper.', max_length=50)),
                ('pdf_file', models.FileField(help_text='The uploaded PDF file of the paper.', upload_to='papers/')),
                ('extracted_text', models.TextField(blank=True, help_text='Full text extracted from the PDF.')),
                ('page_count', models.IntegerField(blank=True, help_text='Number of pages in the PDF.', null=True)),
                ('word_count', models.IntegerField(blank=True, help_text='Approximate word count of the extracted text.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploader', models.ForeignKey(help_text='The user who uploaded this paper.', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField(help_text='Vector embedding representation of the chunk.')),
                ('model_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='papers.paperchunk')),
            ],
        ),
        migrations.AddField(
            model_name='paperchunk',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='papers.researchpaper'),
        ),
        migrations.CreateModel(
            name='PaperAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('affiliation', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_corresponding', models.BooleanField(default=False)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='papers.researchpaper')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['title'], name='papers_rese_title_5a7356_idx'),
        ),
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['research_area'], name='papers_rese_researc_5ad256_idx'),
        ),
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['status'], name='papers_rese_status_381682_idx'),
        ),
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['created_at'], name='papers_rese_created_a73637_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paperchunk',
            unique_together={('paper', 'chunk_index')},
        ),
    ]
