# Generated by Django 4.2.30 on 2026-09-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperchunk',
            name='end_offset',
            field=models.IntegerField(default=0, help_text='Character end offset within extracted text.'),
        ),
        migrations.AddField(
            model_name='paperchunk',
            name='page_number',
            field=models.IntegerField(blank=True, default=1, help_text='PDF page number where this chunk originates.', null=True),
        ),
        migrations.AddField(
            model_name='paperchunk',
            name='section',
            field=models.CharField(blank=True, default='Body', help_text='Detected academic section header.', max_length=200),
        ),
        migrations.AddField(
            model_name='paperchunk',
            name='start_offset',
            field=models.IntegerField(default=0, help_text='Character start offset within extracted text.'),
        ),
    ]
