# Generated by Django 4.2.30 on 2026-09-16 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papers', '0002_paperchunk_end_offset_paperchunk_page_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='citation_count',
            field=models.IntegerField(blank=True, default=0, help_text='Citation count reported by external source.', null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='External unique identifier or cluster ID.', max_length=255),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='external_url',
            field=models.URLField(blank=True, default='', help_text='Original external URL / paper link.', max_length=1024),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='is_external',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this paper was discovered externally rather than uploaded.'),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='publication_date',
            field=models.DateField(blank=True, db_index=True, help_text='Actual date when paper was published.', null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='source',
            field=models.CharField(choices=[('USER_UPLOAD', 'User Upload'), ('GOOGLE_SCHOLAR', 'Google Scholar'), ('EXTERNAL', 'External Source')], db_index=True, default='USER_UPLOAD', help_text='Source of the research paper.', max_length=50),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='The uploaded PDF file of the paper.', null=True, upload_to='papers/'),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='uploader',
            field=models.ForeignKey(blank=True, help_text='The user who uploaded this paper, or null for externally discovered papers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_papers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['is_external', 'created_at'], name='papers_rese_is_exte_05c6da_idx'),
        ),
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['source', 'external_id'], name='papers_rese_source_4a1f9d_idx'),
        ),
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['publication_date'], name='papers_rese_publica_f89a0d_idx'),
        ),
    ]
