# Generated by Django 4.2.30 on 2026-09-10 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('PAPER_UPLOAD', 'Paper Upload'), ('PAPER_EDIT', 'Paper Edit'), ('AI_ANALYSIS', 'AI Analysis'), ('EVALUATION', 'Evaluation'), ('COLLABORATION', 'Collaboration'), ('PROJECT', 'Project'), ('SEARCH', 'Search'), ('LOGIN', 'Login')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='papers.researchpaper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='dashboard_r_user_id_a2fc83_idx')],
            },
        ),
    ]
